services:
  web:
    build: 
      context: .
      target: base
    ports:
      - '8063:80'
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
